# future scaling

# standization and normalization

In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [51]:
#load _titanic dataset
df=sns.load_dataset('titanic')

In [52]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [53]:
df2=df[["survived","pclass","age","parch","sibsp"]]
df2.head()

survived  pclass   age  parch  sibsp
0         0       3  22.0      0      1
1         1       1  38.0      0      1
2         1       3  26.0      0      0
3         1       1  35.0      0      1
4         0       3  35.0      0      0

In [54]:
df3=df2.fillna(df2.mean())
df3.head()

survived  pclass   age  parch  sibsp
0         0       3  22.0      0      1
1         1       1  38.0      0      1
2         1       3  26.0      0      0
3         1       1  35.0      0      1
4         0       3  35.0      0      0

In [67]:
x=df3.drop(columns="survived",axis=1)  # survived is a dependent furture
y=df3["survived"]
print("shape of x",x.shape)
print("shape of y",y.shape)

shape of x (891, 4)
shape of y (891,)


In [56]:
x.head()

pclass   age  parch  sibsp
0       3  22.0      0      1
1       1  38.0      0      1
2       3  26.0      0      0
3       1  35.0      0      1
4       3  35.0      0      0

In [57]:
# import liberary furture scaling
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler


In [58]:
from sklearn.model_selection import train_test_split

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=51) # slpit dataset xtrain and y train,tes

In [69]:
# standardscaler
sc=StandardScaler()

In [70]:
sc

StandardScaler()

In [71]:
sc.fit() # fit x_train datasetx_train

StandardScaler()

In [72]:
sc.mean_

array([ 2.30617978, 29.55409121,  0.39185393,  0.54775281])

In [73]:
x_train.describe() # alll value fit

pclass         age       parch       sibsp
count  712.000000  712.000000  712.000000  712.000000
mean     2.306180   29.554091    0.391854    0.547753
std      0.844651   13.000763    0.797035    1.141455
min      1.000000    0.420000    0.000000    0.000000
25%      1.750000   22.000000    0.000000    0.000000
50%      3.000000   29.699118    0.000000    0.000000
75%      3.000000   35.000000    0.000000    1.000000
max      3.000000   71.000000    5.000000    8.000000

In [74]:
x_train_trans=sc.transform(x_train) # transform of data
x_test_tra=sc.transform(x_test)


In [75]:
x_train_trans

array([[ 0.8220055 , -0.42751304, -0.49198545, -0.48020963],
       [ 0.8220055 ,  1.997125  , -0.49198545, -0.48020963],
       [ 0.8220055 , -1.42815732, -0.49198545, -0.48020963],
       ...,
       [ 0.8220055 ,  1.41983023,  3.27461284,  0.39648077],
       [ 0.8220055 ,  0.01116307,  0.76354731,  2.14986159],
       [ 0.8220055 , -0.08113618, -0.49198545, -0.48020963]])

In [77]:
# 2d array convert datafraam
x_train_trans_dataframe=pd.DataFrame(x_train_trans,columns=["pclass","age","parch","sibsp"])
x_train_trans_dataframe=pd.DataFrame(x_test_tra,columns=["pclass","age","parch","sibsp"])

In [78]:
x_train_trans_dataframe.head()

pclass       age     parch     sibsp
0 -1.547500  0.804049 -0.491985 -0.480210
1  0.822005  0.188268 -0.491985 -0.480210
2  0.822005  0.034323 -0.491985 -0.480210
3 -1.547500  0.011163 -0.491985 -0.480210
4 -0.362747  0.342213  0.763547  0.396481

In [88]:
x_train_trans_dataframe.describe()

pclass         age       parch       sibsp
count  179.000000  179.000000  179.000000  179.000000
mean     0.014520    0.055566   -0.064122   -0.107984
std      0.951660    1.002754    1.057229    0.814738
min     -1.547500   -2.210969   -0.491985   -0.480210
25%     -0.362747   -0.465999   -0.491985   -0.480210
50%      0.822005    0.011163   -0.491985   -0.480210
75%      0.822005    0.419186   -0.491985    0.396481
max      0.822005    3.882955    7.041211    6.533314

# mean_max)scaler

In [79]:
mns=MinMaxScaler()

In [80]:
mns.fit(x_train)

MinMaxScaler()

In [81]:
mns_x_train_tr=mns.transform(x_train)

mns_x_test_tr=mns.transform(x_test)


In [83]:
mns_x_train_tr

array([[1.        , 0.33408898, 0.        , 0.        ],
       [1.        , 0.78039105, 0.        , 0.        ],
       [1.        , 0.14990082, 0.        , 0.        ],
       ...,
       [1.        , 0.67412865, 0.6       , 0.125     ],
       [1.        , 0.4148359 , 0.2       , 0.375     ],
       [1.        , 0.39784642, 0.        , 0.        ]])

In [85]:
# convert dataframe
mns_data_fraame=pd.DataFrame(mns_x_train_tr,columns=["pclass","age","parch","sibsp"])

In [86]:
mns_data_fraame.head()

pclass       age  parch  sibsp
0     1.0  0.334089    0.0    0.0
1     1.0  0.780391    0.0    0.0
2     1.0  0.149901    0.0    0.0
3     1.0  0.249079    0.0    0.0
4     1.0  0.414836    0.4    1.0

In [87]:
mns_data_fraame.describe()

pclass         age       parch       sibsp
count  712.000000  712.000000  712.000000  712.000000
mean     0.653090    0.412781    0.078371    0.068469
std      0.422326    0.184199    0.159407    0.142682
min      0.000000    0.000000    0.000000    0.000000
25%      0.375000    0.305752    0.000000    0.000000
50%      1.000000    0.414836    0.000000    0.000000
75%      1.000000    0.489940    0.000000    0.125000
max      1.000000    1.000000    1.000000    1.000000

In [89]:
print("thanku..........................")

thanku..........................
